server:
  verbosity: 1
  username: "_unbound"
  directory: "/opt/unbound/etc/unbound"
  chroot: ""
  do-daemonize: no
  module-config: "validator iterator"

# Include modular configuration files
include-toplevel: "/opt/unbound/etc/unbound/conf.d/*.conf"
include-toplevel: "/opt/unbound/etc/unbound/zones.d/*.conf"
